services:
  kong:
    container_name: kong-gateway
    build:
      context: .
    image: wesley00s/kong-gateway:latest
    restart: unless-stopped
    networks:
      - kong-net

    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"