name: Kong API Gateway CI/CD

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

env:
  IMAGE_NAME: wesley00s/kong-gateway

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate Kong Config
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/kong/declarative:/kong/declarative \
            kong:3.9.1 kong config parse /kong/declarative/kong.yml

      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME:${{ github.sha }} .
      - name: Push to Docker Hub
        if: github.event_name != 'pull_request'
        run: |
          docker tag $IMAGE_NAME:${{ github.sha }} $IMAGE_NAME:latest
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker push $IMAGE_NAME:${{ github.sha }}
          docker push $IMAGE_NAME:latest